[theme]
# Primary accent color for interactive elements.
primaryColor = "#74BEE0"

# Background color for the main content area.
backgroundColor = "#0B0B0C"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "ff8300"

# Color used for almost all text.
textColor = "001fff"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
